### ISSUE TITLE
Option to watch until every watched item changes

### ISSUE THREAD

**Issue by zdila** [Download/just-wait#3]
Currently just-wait fires if anything changes in any of the comma delimited patterns. What we need is to watch two directories (files) and fire not before both has changed.

**Comment by Download** [comment]
Hi, sorry for the late response. 

I guess you are asking for AND/OR operators :)
I am open to PRs but I won't be changing this module much myself as I don't need this feature.

I think a simple workaround may be to chain two just-wait commands:

``` sh
just-wait file1 && just-wait file2 && echo Both files exist at this point
```
